---
- name: Play to install httpd package
  hosts: alc  
  become: true
  gather_facts: false
  become_user: root
  tasks:
   - name: Task to copy my repo file to remote server
     copy:
      src: /etc/yum.repos.d/rhel95.repo
      dest: /etc/yum.repos.d/rhel95.repo
   - name: Task to install httpd package
     yum:
      name: httpd
      state: latest
  - name: Task to add the port in the firewalld
     firewalld:
      service: http
      permanent: true
      state: enabled
   - name: Create index.html
     copy:
      dest: /var/www/html/index.html
      content: "<html><h1><center>This is build by Ansible</center></h1></html>"
      mode: '0644'
   - name: Start http service
     service:
      name: httpd
      state: started
      enabled: yes
...