---
- name: create a volume group using pv /dev/sdd
  hosts: localhost
  become: true
  remote_user: ansible
  gather_facts: false
  tasks:
    - name: create vg 
      lvg: 
       vg: logsvg
       pvs: /dev/sdd
       pesize: 32
    - name: Create a volume
      lvol:
       vg: logsvg
       lv: loglv01
       size: 512
       pvs: /dev/sdd
    - name: create a filesystem
      filesystem:
       fstype : xfs
       dev: /dev/logsvg/loglv01
    - name: Create mount point if it doesnt exists. Do this before it attempts to mount
      file: 
       path: /logsfs
       state: directory
       mode: 0755
    - name: mount the filesystem 
      mount: 
       path: /logsfs
       src: /dev/logsvg/loglv01
       fstype: xfs
       state: mounted
...                
